on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    # https://github.com/zmkfirmware/zmk/releases
    # https://zmk.dev/blog
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
